### Question 1:
#### Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [4]:
import numpy as np
x = np.array([8, 20])
y = np.array([5, 20])
print("Original numbers:")
print("Array 1" , x)
print("Array 2" , y)

print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))


Original numbers:
Array 1 [ 8 20]
Array 2 [ 5 20]
Comparison - greater
[ True False]
Comparison - greater_equal
[ True  True]
Comparison - less
[False False]
Comparison - less_equal
[False  True]


### Question 2:
#### Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [5]:
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array1=np.ones(10)
print("An array of 10 ones:")
print(array1)
array2=np.ones(10)*5
print("An array of 10 fives:")
print(array2)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


### Question 3:
#### Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array

In [8]:
arr = [[14, 17, 12],    
       [15, 6, 27],   
       [23, 2, 54]]

print("\nSum of arr : ", np.sum(arr)) 


Sum of arr :  170


In [10]:
print("Sum of arr(Column) : ", np.sum(arr, axis = 0))  
print("Sum of arr(Row) : ", np.sum(arr, axis = 1))

Sum of arr(Column) :  [52 25 93]
Sum of arr(Row) :  [43 48 79]


### Question 4:
#### Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [ ]:
array1 = np.array([[10, 20, 30], [40, 50, 60]])
array2 = np.array([[2, 3, 4], [4, 6, 8]]

In [12]:
print(np.add(array1, array2))

[6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]


In [15]:
a = np.arange(12, dtype = np.float_).reshape(4,3)

In [16]:
a

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [19]:
print ('First array:' )
print (a) 
print ('\n')  

print ('Second array:' )
b = np.array([10,10,10]) 
print (b) 
print ('\n'  )

print ('Add the two arrays:' )
print (np.add(a,b)) 
print ('\n')  

print ('Subtract the two arrays:' )
print (np.subtract(a,b)) 
print ('\n')

print ('Multiply the two arrays:')
print (np.multiply(a,b))
print ('\n'  )

print ('Divide the two arrays:' )
print (np.divide(a,b))

First array:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


Second array:
[10 10 10]


Add the two arrays:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]
 [19. 20. 21.]]


Subtract the two arrays:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]
 [ -1.   0.   1.]]


Multiply the two arrays:
[[  0.  10.  20.]
 [ 30.  40.  50.]
 [ 60.  70.  80.]
 [ 90. 100. 110.]]


Divide the two arrays:
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]]


### Question 5:
#### Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in degree.


In [23]:
# Angle given in Degree
print("sine: ")
print(np.sin(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))


sine: 
[0.         0.5        0.70710678 0.8660254  1.        ]


In [24]:
print("cosine:")
print(np.cos(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))


cosine:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


In [25]:
print("tangent: " )
print(np.tan(np.array((0., 30., 45., 60., 90.)) * np.pi / 180.))

tangent: 
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]
